# Descargar la imagen oficial de PostgreSQL desde Docker Hub
FROM postgres:latest

# Copia los scripts de DDL y DML al directorio de Docker
COPY 1_DDL_Monedas_Docker.sql /docker-entrypoint-initdb.d/
COPY 2_DML_Monedas_Docker.sql /docker-entrypoint-initdb.d/